services:
  - type: web
    name: netfive-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    envVars:
      - key: PORT
        generateValue: true
